import Head from 'next/head'
import Image from 'next/image'
import { NextPage } from 'next'
import Banner from '@/components/banner'
import Navbar from '@/components/navbar'
import Projects from '@/components/projects'
import Home from '@/components/home'
import Style from '@/scss/page.module.scss'

const Page: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Home/>
        <Navbar/>
        <div className={Style.wrapper}>
          <Banner/>
        </div>
        <Projects/>
      </main>
    </>
  )
}

export default Page;